'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("getUSDCAD.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''BEGIN TRAN;
        '''IF EXISTS (SELECT * FROM [&lt;&lt;TABLE&gt;&gt;].[YCONVERTION] WHERE CURDEN_0 = &apos;&lt;&lt;CURDEN&gt;&gt;&apos; and CUR_0 = &apos;&lt;&lt;CUR&gt;&gt;&apos; )
        '''update [&lt;&lt;DATABASE&gt;&gt;].[&lt;&lt;TABLE&gt;&gt;].[YCONVERTION] set
        '''[CURDEN_0] =&apos;&lt;&lt;CURDEN&gt;&gt;&apos;,
        '''[CUR_0] =&apos;&lt;&lt;CUR&gt;&gt;&apos;,
        '''[CHGSTRDAT_0] =&apos;&lt;&lt;CHGSTRDAT&gt;&gt;&apos;,
        '''[CHGRAT_0] =&lt;&lt;CHGRAT&gt;&gt;,
        '''[REVCOURS_0] =&lt;&lt;REVCOURS&gt;&gt;
        '''WHERE CURDEN_0 = &apos;&lt;&lt;CURDEN&gt;&gt;&apos; and CUR_0 = &apos;&lt;&lt;CUR&gt;&gt;&apos;
        '''else
        '''Insert into [&lt;&lt;DATABASE&gt;&gt;].[&lt;&lt;TABLE&gt;&gt;].[YCONVERTION]  
        '''([CURDEN_0],[CUR_0], [CHGSTRDAT_0],[CHGRAT_0],[REVCOURS_0])
        '''VALUES
        '''(
        '''&apos;&lt;&lt;CURDEN&gt;&gt;&apos;,
        '''&apos;&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property insertOrUpdateConvertion() As String
            Get
                Return ResourceManager.GetString("insertOrUpdateConvertion", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
